export const NavLinksList = {
	LINK_EN: [
		{
			name: 'Solutions',
			children: [
				{ name: 'AI Prototype to Production', url: '/ai-prototype-to-production' },
				{ name: 'Lovable to Production', url: '/from-lovable-to-production' },
				{ name: 'V0 to Production', url: '/from-v0-to-production' },
				{ name: 'Bolt to Production', url: '/from-bolt-to-production' },
				{ name: 'Cursor to Production', url: '/from-cursor-to-production' },
				{ name: 'Production Readiness Checklist', url: '/production-readiness-checklist' },
			],
		},
		{ name: 'Pricing', url: '#pricing' },
		{ name: 'About', url: '/about' },
		{ name: 'Blog', url: '/blog' },
		{ name: 'Services', url: '/services' },
		{ name: 'Case Studies', url: '/case-studies' },
	],
	LINK_ZH: [
		{
			name: '解决方案',
			children: [
				{ name: 'AI 原型到生产', url: '/ai-prototype-to-production' },
				{ name: 'Lovable 到生产', url: '/from-lovable-to-production' },
				{ name: 'V0 到生产', url: '/from-v0-to-production' },
				{ name: 'Bolt 到生产', url: '/from-bolt-to-production' },
				{ name: 'Cursor 到生产', url: '/from-cursor-to-production' },
				{ name: '生产就绪清单', url: '/production-readiness-checklist' },
			],
		},
		{ name: '定价', url: '#pricing' },
		{ name: '关于', url: '/about' },
		{ name: '博客', url: '/blog' },
		{ name: '服务', url: '/services' },
		{ name: '案例研究', url: '/case-studies' },
	],
	LINK_ES: [
		{
			name: 'Soluciones',
			children: [
				{ name: 'Prototipo IA a producción', url: '/ai-prototype-to-production' },
				{ name: 'Lovable a producción', url: '/from-lovable-to-production' },
				{ name: 'V0 a producción', url: '/from-v0-to-production' },
				{ name: 'Bolt a producción', url: '/from-bolt-to-production' },
				{ name: 'Cursor a producción', url: '/from-cursor-to-production' },
				{ name: 'Checklist de producción', url: '/production-readiness-checklist' },
			],
		},
		{ name: 'Precios', url: '#pricing' },
		{ name: 'Acerca de', url: '/about' },
		{ name: 'Blog', url: '/blog' },
		{ name: 'Servicios', url: '/services' },
		{ name: 'Casos de Estudio', url: '/case-studies' },
	],
	LINK_RU: [
		{
			name: 'Решения',
			children: [
				{ name: 'AI-прототип в продакшен', url: '/ai-prototype-to-production' },
				{ name: 'Lovable в продакшен', url: '/from-lovable-to-production' },
				{ name: 'V0 в продакшен', url: '/from-v0-to-production' },
				{ name: 'Bolt в продакшен', url: '/from-bolt-to-production' },
				{ name: 'Cursor в продакшен', url: '/from-cursor-to-production' },
				{ name: 'Production checklist', url: '/production-readiness-checklist' },
			],
		},
		{ name: 'Цены', url: '#pricing' },
		{ name: 'О нас', url: '/about' },
		{ name: 'Блог', url: '/blog' },
		{ name: 'Услуги', url: '/services' },
		{ name: 'Кейсы', url: '/case-studies' },
	],
	LINK_JA: [
		{
			name: 'ソリューション',
			children: [
				{ name: 'AIプロトタイプを本番へ', url: '/ai-prototype-to-production' },
				{ name: 'Lovableを本番へ', url: '/from-lovable-to-production' },
				{ name: 'V0を本番へ', url: '/from-v0-to-production' },
				{ name: 'Boltを本番へ', url: '/from-bolt-to-production' },
				{ name: 'Cursorを本番へ', url: '/from-cursor-to-production' },
				{ name: '本番対応チェックリスト', url: '/production-readiness-checklist' },
			],
		},
		{ name: '価格', url: '#pricing' },
		{ name: 'アバウト', url: '/about' },
		{ name: 'ブログ', url: '/blog' },
		{ name: 'サービス', url: '/services' },
		{ name: 'ケーススタディ', url: '/case-studies' },
	],
	LINK_AR: [
		{
			name: 'الحلول',
			children: [
				{ name: 'من نموذج AI إلى الإنتاج', url: '/ai-prototype-to-production' },
				{ name: 'Lovable إلى الإنتاج', url: '/from-lovable-to-production' },
				{ name: 'V0 إلى الإنتاج', url: '/from-v0-to-production' },
				{ name: 'Bolt إلى الإنتاج', url: '/from-bolt-to-production' },
				{ name: 'Cursor إلى الإنتاج', url: '/from-cursor-to-production' },
				{ name: 'قائمة جاهزية الإنتاج', url: '/production-readiness-checklist' },
			],
		},
		{ name: 'التسعير', url: '#pricing' },
		{ name: 'حول', url: '/about' },
		{ name: 'مدونة', url: '/blog' },
		{ name: 'خدمات', url: '/services' },
		{ name: 'دراسات حالة', url: '/case-studies' },
	],
	LINK_FR: [
		{
			name: 'Solutions',
			children: [
				{ name: 'Prototype IA à la production', url: '/ai-prototype-to-production' },
				{ name: 'Lovable à la production', url: '/from-lovable-to-production' },
				{ name: 'V0 à la production', url: '/from-v0-to-production' },
				{ name: 'Bolt à la production', url: '/from-bolt-to-production' },
				{ name: 'Cursor à la production', url: '/from-cursor-to-production' },
				{ name: 'Checklist production', url: '/production-readiness-checklist' },
			],
		},
		{ name: 'Tarification', url: '#pricing' },
		{ name: 'À propos', url: '/about' },
		{ name: 'Blog', url: '/blog' },
		{ name: 'Services', url: '/services' },
		{ name: 'Études de cas', url: '/case-studies' },
	],
};
